In [20]:
import pandas as pd
import numpy as np

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [199]:
# test_df = pd.DataFrame([[90, [1,2,3], 'This is my text'],
#               [80, [4, 5],  'I have too many goddamn cellphone'],
#               [70, []    ,  'I have too many goddamn cellphones'],
#               [60, []    ,  'You have got to be kidding me'],
#               [70, [1,1,1], "I'm not sure what you mean"],
#               [10, [],      "I'm sure what you mean"],
#               [0,  [1, 9],  "I'm really not sure what you mean"],
#               [0,  [2, 3],  "My name is Jonathan Papir"],
#               [2,  [],      "Purple sharks are great"]],
#             columns=['price', 'price_list', 'post_text'])
# test_df

In [200]:
test_df = pd.DataFrame([[80, [4, 5],  'I have too many goddamn cellphone'],
              [70, []    ,  'I have too many goddamn cellphones'],
              [70, [1,1,1], "I'm not sure what you mean"],
              [10, [],      "I'm sure what you mean"],
              [0,  [1, 9],  "I'm really not sure what you mean"]],
            columns=['price', 'price_list', 'post_text'])
test_df

price price_list                           post_text
0     80     [4, 5]   I have too many goddamn cellphone
1     70         []  I have too many goddamn cellphones
2     70  [1, 1, 1]          I'm not sure what you mean
3     10         []              I'm sure what you mean
4      0     [1, 9]   I'm really not sure what you mean

In [201]:
text_for_comparison_all = test_df['post_text']
vect = TfidfVectorizer(min_df=1, stop_words='english')
tfidf_all = vect.fit_transform(text_for_comparison_all)
pairwise_similarity_all = tfidf_all * tfidf_all.T

In [202]:
pairwise_array_all = pairwise_similarity_all.toarray()
np.fill_diagonal(pairwise_array_all, np.nan)

In [203]:
pairwise_array_all[0]

array([       nan, 0.39427569, 0.        , 0.        , 0.        ])

In [204]:
arg_where_arr = np.argwhere(pairwise_array_all > 0.3)
arg_where_arr

array([[0, 1],
       [1, 0],
       [2, 3],
       [2, 4],
       [3, 2],
       [3, 4],
       [4, 2],
       [4, 3]])

In [205]:
sorted_arg_where_arr = np.sort(arg_where_arr,axis=-1)
sorted_arg_where_arr

array([[0, 1],
       [0, 1],
       [2, 3],
       [2, 4],
       [2, 3],
       [3, 4],
       [2, 4],
       [3, 4]])

In [206]:
sorted_arg_where_arr = np.sort(arg_where_arr,axis=-1)
unique_1, idx_1 = np.unique(sorted_arg_where_arr, return_index = True, axis=0)
unique_1, idx_1

(array([[0, 1],
        [2, 3],
        [2, 4],
        [3, 4]]),
 array([0, 2, 3, 5]))

In [197]:
test_df

price price_list                           post_text
0     80     [4, 5]   I have too many goddamn cellphone
1     70         []  I have too many goddamn cellphones
2     70  [1, 1, 1]          I'm not sure what you mean
3     10         []              I'm sure what you mean
4      0     [1, 9]   I'm really not sure what you mean

In [198]:
test_df.iloc[idx_1]

IndexError: positional indexers are out-of-bounds

In [125]:
tupList = list(map(tuple, arg_where_arr))
tupList

[(1, 2), (2, 1), (4, 5), (4, 6), (5, 4), (5, 6), (6, 4), (6, 5)]

In [126]:
tupListWoDup = list(set(map(tuple, map(sorted, tupList))))

# Printing the list of tuples 
print("List of Tuples after removal of duplicates : " + str(tupListWoDup))

List of Tuples after removal of duplicates : [(4, 6), (4, 5), (1, 2), (5, 6)]


In [ ]:
no_dups_at_all = []
for tup in tupListWoDup:
    if 

In [56]:
drop_idx = np.argwhere(pairwise_array_all > 0.3)[:,1:].flatten()

In [109]:
np.delete(arg_where_arr, [4, 5], axis=0)

array([[1, 2],
       [2, 1],
       [4, 5],
       [4, 6],
       [6, 4],
       [6, 5]])

In [116]:
arr_len = len(arg_where_arr)

for i in np.arange(arr_len, -1, -1):
    dup_idx = arg_where_arr[-1, 1]
    print(F"dup_idx {dup_idx}")
    #arg_where_arr[arg_where_arr[:,0] == idx_to_drop] 
    idx_to_drop = np.where(arg_where_arr[:,0] == dup_idx)
    print(F"idx_to_drop {idx_to_drop}")
    arg_where_arr = np.delete(arg_where_arr, idx_to_drop, axis=0)
    print(new_arr)

dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]
dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]
dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]
dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]
dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]
dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]
dup_idx 5
idx_to_drop (array([], dtype=int64),)
[[1 2]
 [2 1]
 [4 5]
 [4 6]
 [6 4]
 [6 5]]


In [112]:
new_arr

array([[1, 2],
       [2, 1],
       [4, 5],
       [4, 6],
       [6, 4],
       [6, 5]])

In [79]:
arg_where_arr[:5]

array([5, 6])

In [85]:
arg_where_arr[arg_where_arr[:,0] == 5]

array([[5, 4],
       [5, 6]])

In [58]:
drop_idx

array([2, 1, 5, 6, 4, 6, 4, 5])

In [59]:
df_idx = test_df.index.values
df_idx

array([0, 1, 2, 3, 4, 5, 6])

In [60]:
match_list = []
for idx in df_idx:
    match_list.append(str(idx in drop_idx))

In [61]:
test_df['match'] = match_list

In [62]:
test_df

price price_list                           post_text  match
0     90  [1, 2, 3]                     This is my text  False
1     80     [4, 5]   I have too many goddamn cellphone   True
2     70         []  I have too many goddamn cellphones   True
3     60         []       You have got to be kidding me  False
4     70  [1, 1, 1]          I'm not sure what you mean   True
5     10         []              I'm sure what you mean   True
6      0     [1, 9]   I'm really not sure what you mean   True

In [117]:
# Program to remove duplicate tuples 

# Creating and printing the list of tuples
tupList = [(1, 2), (2, 1), (4, 5), (4, 6), (5, 4), (5, 6), (6, 4), (6,5)]
print("Initial List of Tuples : " + str(tupList))

# Removing all duplicate tuples from the list
tupListWoDup = list(set(map(tuple, map(sorted, tupList))))

# Printing the list of tuples 
print("List of Tuples after removal of duplicates : " + str(tupListWoDup))

Initial List of Tuples : [(1, 2), (2, 1), (4, 5), (4, 6), (5, 4), (5, 6), (6, 4), (6, 5)]
List of Tuples after removal of duplicates : [(4, 6), (4, 5), (1, 2), (5, 6)]


In [63]:
indices = []
for i, row in test_df.iterrows():
    indices.append(i)
    try:
        test_df = test_df.drop(
        index=[item for item in row["match"] if item in indices], inplace=True, errors="ignore"
    )
    except:
        pass

In [64]:
test_df

In [ ]:
# def remove_duplicate_text(x):
#     text_for_comparison = x
#     vect = TfidfVectorizer(min_df=1, stop_words='english')
#     tfidf = vect.fit_transform(text_for_comparison)
#     pairwise_sim = tfidf * tfidf.T
#     pairwise_arr = pairwise_sim.toarray()

# With list comprehension

In [209]:
import textdistance

test_df = pd.DataFrame([[90, [1,2,3], 'This is my text'],
              [80, [4, 5],  'I have too many goddamn cellphone'],
              [70, []    ,  'I have too many goddamn cellphones'],
              [60, []    ,  'You have got to be kidding me'],
              [70, [1,1,1], "I'm not sure what you mean"],
              [10, [],      "I'm sure what you mean"],
              [0,  [1, 9],  "I'm really not sure what you mean"],
              [0,  [2, 3],  "My name is Jonathan Papir"],
              [2,  [],      "Purple sharks are great"]],
            columns=['price', 'price_list', 'post_text'])

# Calculate similarities between rows
# and save corresponding indexes in a new column "match"
test_df["match"] = test_df["post_text"].map(
    lambda x: [
        i
        for i, text in enumerate(test_df["post_text"])
        if textdistance.jaro_winkler(x, text) >= 0.7
    ]
)

# Iterate to remove similar rows (keeping only the first one)
indices = []
for i, row in test_df.iterrows():
    indices.append(i)
    test_df = test_df.drop(
        index=[item for item in row["match"] if item not in indices], errors="ignore"
    )

In [210]:
test_df

price price_list                          post_text      match
0     90  [1, 2, 3]                    This is my text        [0]
1     80     [4, 5]  I have too many goddamn cellphone     [1, 2]
3     60         []      You have got to be kidding me        [3]
4     70  [1, 1, 1]         I'm not sure what you mean  [4, 5, 6]
7      0     [2, 3]          My name is Jonathan Papir        [7]
8      2         []            Purple sharks are great        [8]

# Without List Comprehension

In [211]:
import textdistance

test_df = pd.DataFrame([[90, [1,2,3], 'This is my text'],
              [80, [4, 5],  'I have too many goddamn cellphone'],
              [70, []    ,  'I have too many goddamn cellphones'],
              [60, []    ,  'You have got to be kidding me'],
              [70, [1,1,1], "I'm not sure what you mean"],
              [10, [],      "I'm sure what you mean"],
              [0,  [1, 9],  "I'm really not sure what you mean"],
              [0,  [2, 3],  "My name is Jonathan Papir"],
              [2,  [],      "Purple sharks are great"]],
            columns=['price', 'price_list', 'post_text'])

# Calculate similarities between rows
# and save corresponding indexes in a new column "match"
test_df["match"] = test_df["post_text"].map(
    lambda x: [
        i
        for i, text in enumerate(test_df["post_text"])
        if textdistance.jaro_winkler(x, text) >= 0.7
    ]
)

# Iterate to remove similar rows (keeping only the first one)
indices = []
for i, row in test_df.iterrows():
    indices.append(i)
    drop_idx = []
    for item in row['match']:
        if item not in indices:
            drop_idx.append(item)
    test_df = test_df.drop(index=drop_idx, errors="ignore")

In [212]:
test_df

price price_list                          post_text      match
0     90  [1, 2, 3]                    This is my text        [0]
1     80     [4, 5]  I have too many goddamn cellphone     [1, 2]
3     60         []      You have got to be kidding me        [3]
4     70  [1, 1, 1]         I'm not sure what you mean  [4, 5, 6]
7      0     [2, 3]          My name is Jonathan Papir        [7]
8      2         []            Purple sharks are great        [8]

In [174]:
duplicate_df = pd.read_csv('./duplicate_posts.csv')
duplicate_df

price_list  \
0                               ['$90', '$60', '$40']   
1                               ['$30', '$35', '$45']   
2                        ['$40', '$40', '$45', '$45']   
3                        ['$30', '$30', '$60', '$90']   
4                              ['$60', '$50', '$100']   
5       ['$100', '$115', '$130', '$65', '$30', '$60']   
6                 ['$40', '$40', '$40', '$40', '$40']   
7                               ['$50', '$10', '$50']   
8                               ['$50', '$10', '$50']   
9                             ['$50', '$100', '$135']   
10                              ['$30', '$35', '$45']   
11              ['$30', '$50', '$500', '$900', '$60']   
12  ['$40', '$80', '$40', '$10', '$40', '$30', '$4...   
13                              ['$90', '$60', '$40']   
14                              ['$25', '$45', '$25']   
15         ['$35', '$35', '$40', '$40', '$55', '$80']   
16         ['$35', '$35', '$40', '$40', '$55', '$80']   
17                ['$40', '$40', '$40', '$40', '$40']   
18                       ['$45', '$55', '$40', '$50']   
19                              ['$65', '$55', '$55']   
20                    ['$200', '$60,000', '$240,000']   
21                       ['$20', '$25', '$30', '$30']   
22                              ['$65', '$55', '$55']   

                                            post_text  
0   \n\n\n\n\nDon't wait to get a tutor! This appl...  
1   \n\n\n\n\nFeel free to text me at 909-640-3570...  
2   \n\n\n\n\n!!** ALL SUBJECTS PROFESSIONAL TUTOR...  
3   \n\n\n\n\nExperienced, qualified Middle School...  
4   \n\n\n\n\nI have been doing mathematics tutori...  
5   \n\n\n\n\nLearn better, faster - and have more...  
6   \n\n\n\n\n★★ College Math Tutor★ Calculus I ,I...  
7   \n\n\n\n\nTutoring rate. $50/hr, Group Rate, $...  
8   \n\n\n\n\nTutoring rate. $50/hr, Group Rate, $...  
9   \n\n\n\n\nI hope everything is fine and I am g...  
10  \n\n\n\n\nFeel free to text me at 909-640-3570...  
11  \n\n\n\n\nVirtual Tutoring!\n\nHi! I'm Sam. I'...  
12  \n\n\n\n\nNEED A PRIVATE TUTOR?\n$40/hour for ...  
13  \n\n\n\n\nDon't wait to get a tutor! This appl...  
14  \n\n\n\n\nI'm a professional, NTA certified ma...  
15  \n\n\n\n\nHello,\n\nI am an engineering workin...  
16  \n\n\n\n\nHello, \n\nI am an engineering worki...  
17  \n\n\n\n\n★★ College Math Tutor★ Calculus I ,I...  
18  \n\n\n\n\nFormer UC-Berkeley economics Ph.D. s...  
19  \n\n\n\n\nPark Tutoring \n\n\nOne on One Tutor...  
20  \n\n\n\n\ncheck out my website!\nmd-maker.com\...  
21  \n\n\n\n\nPlease visit us at www.sharpmindclas...  
22  \n\n\n\n\nPark Tutoring \n\n\nOne on One Tutor...

In [176]:
import textdistance
# Calculate similarities between rows
# and save corresponding indexes in a new column "match"
duplicate_df["match"] = duplicate_df["post_text"].map(
    lambda x: [
        i
        for i, text in enumerate(duplicate_df["post_text"])
        if textdistance.jaro_winkler(x, text) >= 0.9
    ]
)

# Iterate to remove similar rows (keeping only the first one)
indices = []
for i, row in duplicate_df.iterrows():
    print(i)
    indices.append(i)
    duplicate_df = duplicate_df.drop(
        index=[item for item in row["match"] if item not in indices], errors="ignore"
    )

In [177]:
duplicate_df

price_list  \
0                               ['$90', '$60', '$40']   
1                               ['$30', '$35', '$45']   
2                        ['$40', '$40', '$45', '$45']   
3                        ['$30', '$30', '$60', '$90']   
4                              ['$60', '$50', '$100']   
5       ['$100', '$115', '$130', '$65', '$30', '$60']   
6                 ['$40', '$40', '$40', '$40', '$40']   
7                               ['$50', '$10', '$50']   
8                               ['$50', '$10', '$50']   
9                             ['$50', '$100', '$135']   
10                              ['$30', '$35', '$45']   
11              ['$30', '$50', '$500', '$900', '$60']   
12  ['$40', '$80', '$40', '$10', '$40', '$30', '$4...   
13                              ['$90', '$60', '$40']   
14                              ['$25', '$45', '$25']   
15         ['$35', '$35', '$40', '$40', '$55', '$80']   
16         ['$35', '$35', '$40', '$40', '$55', '$80']   
17                ['$40', '$40', '$40', '$40', '$40']   
18                       ['$45', '$55', '$40', '$50']   
19                              ['$65', '$55', '$55']   
20                    ['$200', '$60,000', '$240,000']   
21                       ['$20', '$25', '$30', '$30']   
22                              ['$65', '$55', '$55']   

                                            post_text     match  
0   \n\n\n\n\nDon't wait to get a tutor! This appl...   [0, 13]  
1   \n\n\n\n\nFeel free to text me at 909-640-3570...   [1, 10]  
2   \n\n\n\n\n!!** ALL SUBJECTS PROFESSIONAL TUTOR...       [2]  
3   \n\n\n\n\nExperienced, qualified Middle School...       [3]  
4   \n\n\n\n\nI have been doing mathematics tutori...       [4]  
5   \n\n\n\n\nLearn better, faster - and have more...       [5]  
6   \n\n\n\n\n★★ College Math Tutor★ Calculus I ,I...   [6, 17]  
7   \n\n\n\n\nTutoring rate. $50/hr, Group Rate, $...    [7, 8]  
8   \n\n\n\n\nTutoring rate. $50/hr, Group Rate, $...    [7, 8]  
9   \n\n\n\n\nI hope everything is fine and I am g...       [9]  
10  \n\n\n\n\nFeel free to text me at 909-640-3570...   [1, 10]  
11  \n\n\n\n\nVirtual Tutoring!\n\nHi! I'm Sam. I'...      [11]  
12  \n\n\n\n\nNEED A PRIVATE TUTOR?\n$40/hour for ...      [12]  
13  \n\n\n\n\nDon't wait to get a tutor! This appl...   [0, 13]  
14  \n\n\n\n\nI'm a professional, NTA certified ma...      [14]  
15  \n\n\n\n\nHello,\n\nI am an engineering workin...  [15, 16]  
16  \n\n\n\n\nHello, \n\nI am an engineering worki...  [15, 16]  
17  \n\n\n\n\n★★ College Math Tutor★ Calculus I ,I...   [6, 17]  
18  \n\n\n\n\nFormer UC-Berkeley economics Ph.D. s...      [18]  
19  \n\n\n\n\nPark Tutoring \n\n\nOne on One Tutor...  [19, 22]  
20  \n\n\n\n\ncheck out my website!\nmd-maker.com\...      [20]  
21  \n\n\n\n\nPlease visit us at www.sharpmindclas...      [21]  
22  \n\n\n\n\nPark Tutoring \n\n\nOne on One Tutor...  [19, 22]

In [178]:
indices = []
for i, row in duplicate_df.iterrows():
    print(i)
    indices.append(i)
    duplicate_df = duplicate_df.drop(
        index=[item for item in row["match"] if item not in indices], errors="ignore"
    )

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [179]:
duplicate_df

price_list  \
0                               ['$90', '$60', '$40']   
1                               ['$30', '$35', '$45']   
2                        ['$40', '$40', '$45', '$45']   
3                        ['$30', '$30', '$60', '$90']   
4                              ['$60', '$50', '$100']   
5       ['$100', '$115', '$130', '$65', '$30', '$60']   
6                 ['$40', '$40', '$40', '$40', '$40']   
7                               ['$50', '$10', '$50']   
9                             ['$50', '$100', '$135']   
11              ['$30', '$50', '$500', '$900', '$60']   
12  ['$40', '$80', '$40', '$10', '$40', '$30', '$4...   
14                              ['$25', '$45', '$25']   
15         ['$35', '$35', '$40', '$40', '$55', '$80']   
18                       ['$45', '$55', '$40', '$50']   
19                              ['$65', '$55', '$55']   
20                    ['$200', '$60,000', '$240,000']   
21                       ['$20', '$25', '$30', '$30']   

                                            post_text     match  
0   \n\n\n\n\nDon't wait to get a tutor! This appl...   [0, 13]  
1   \n\n\n\n\nFeel free to text me at 909-640-3570...   [1, 10]  
2   \n\n\n\n\n!!** ALL SUBJECTS PROFESSIONAL TUTOR...       [2]  
3   \n\n\n\n\nExperienced, qualified Middle School...       [3]  
4   \n\n\n\n\nI have been doing mathematics tutori...       [4]  
5   \n\n\n\n\nLearn better, faster - and have more...       [5]  
6   \n\n\n\n\n★★ College Math Tutor★ Calculus I ,I...   [6, 17]  
7   \n\n\n\n\nTutoring rate. $50/hr, Group Rate, $...    [7, 8]  
9   \n\n\n\n\nI hope everything is fine and I am g...       [9]  
11  \n\n\n\n\nVirtual Tutoring!\n\nHi! I'm Sam. I'...      [11]  
12  \n\n\n\n\nNEED A PRIVATE TUTOR?\n$40/hour for ...      [12]  
14  \n\n\n\n\nI'm a professional, NTA certified ma...      [14]  
15  \n\n\n\n\nHello,\n\nI am an engineering workin...  [15, 16]  
18  \n\n\n\n\nFormer UC-Berkeley economics Ph.D. s...      [18]  
19  \n\n\n\n\nPark Tutoring \n\n\nOne on One Tutor...  [19, 22]  
20  \n\n\n\n\ncheck out my website!\nmd-maker.com\...      [20]  
21  \n\n\n\n\nPlease visit us at www.sharpmindclas...      [21]

In [ ]:
import textdistance

test_df = pd.DataFrame([[90, [1,2,3], 'This is my text'],
              [80, [4, 5],  'I have too many goddamn cellphone'],
              [70, []    ,  'I have too many goddamn cellphones'],
              [60, []    ,  'You have got to be kidding me'],
              [70, [1,1,1], "I'm not sure what you mean"],
              [10, [],      "I'm sure what you mean"],
              [0,  [1, 9],  "I'm really not sure what you mean"]],
            columns=['price', 'price_list', 'post_text'])

# Calculate similarities between rows
# and save corresponding indexes in a new column "match"
test_df["match"] = test_df["post_text"].map(
    lambda x:
        new_list = []
        for i, text in enumerate(test_df["post_text"]):
            if textdistance.jaro_winkler(x, text) >= 0.7:
                new_list.append(x)
)

# Iterate to remove similar rows (keeping only the first one)
indices = []
for i, row in test_df.iterrows():
    indices.append(i)
    test_df = test_df.drop(
        index=[item for item in row["match"] if item not in indices], errors="ignore"
    )